apiVersion: v1
kind: Service
metadata:
  name: keda-demo
  labels:
    app: keda-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: keda-demo
  type: ClusterIP